CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar,
  "role" varchar,
  "specialization" varchar,
  "identification_number" varchar,
  "bio" text,
  "profile_photo_path" varchar,
  "password_hash" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "patients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "gender" varchar,
  "date_of_birth" date,
  "blood_type" varchar,
  "phone1" varchar,
  "phone2" varchar,
  "email" varchar,
  "address" varchar,
  "city" varchar,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "allergies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "patient_allergies" (
  "patient_id" integer,
  "allergy_id" integer,
  "notes" text
);

CREATE TABLE "medical_conditions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "patient_conditions" (
  "patient_id" integer,
  "condition_id" integer,
  "diagnosis_date" date,
  "notes" text
);

CREATE TABLE "treatments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar,
  "name" varchar,
  "description" text,
  "base_price" real,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "appointments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" integer,
  "doctor_id" integer,
  "start_datetime" timestamp,
  "end_datetime" timestamp,
  "status" varchar,
  "diagnosis" varchar,
  "notes" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "patient_treatments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" integer,
  "treatment_id" integer,
  "doctor_id" integer,
  "appointment_id" integer,
  "session_date" date,
  "status" varchar,
  "price" real,
  "notes" text
);

CREATE TABLE "invoices" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_number" varchar UNIQUE,
  "patient_id" integer,
  "status" varchar,
  "start_date" date,
  "due_date" date,
  "subtotal_amount" real,
  "discount_amount" real,
  "total_amount" real,
  "notes" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "invoice_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" integer,
  "treatment_id" integer,
  "description" varchar,
  "quantity" real,
  "unit_price" real,
  "total_price" real
);

CREATE TABLE "payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" integer,
  "payment_date" date,
  "amount" real,
  "method" varchar,
  "reference" varchar,
  "notes" text
);

CREATE TABLE "patient_documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" integer,
  "uploaded_by_user_id" integer,
  "file_name" varchar,
  "file_path" varchar,
  "file_type" varchar,
  "uploaded_at" timestamp,
  "description" text
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "action" varchar,
  "entity_type" varchar,
  "entity_id" integer,
  "timestamp" timestamp,
  "details" text
);

CREATE TABLE "expense_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "expenses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "expense_date" date,
  "description" varchar,
  "category_id" integer,
  "amount" real,
  "created_by_user_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "medications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "form" varchar,
  "strength" varchar,
  "default_route" varchar,
  "default_instructions" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "prescriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" integer,
  "doctor_id" integer,
  "appointment_id" integer,
  "issued_at" timestamp,
  "notes" text
);

CREATE TABLE "prescription_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prescription_id" integer,
  "medication_id" integer,
  "medication_name" varchar,
  "dosage" varchar,
  "route" varchar,
  "frequency" varchar,
  "duration" varchar,
  "instructions" text
);

CREATE UNIQUE INDEX "ux_patient_allergies_patient_allergy" ON "patient_allergies" ("patient_id", "allergy_id");

CREATE UNIQUE INDEX "ux_patient_conditions_patient_condition" ON "patient_conditions" ("patient_id", "condition_id");

COMMENT ON COLUMN "users"."role" IS 'admin, doctor, receptionist';

COMMENT ON COLUMN "patients"."status" IS 'active, inactive, archived';

COMMENT ON TABLE "patient_allergies" IS 'Many-to-many between patients and allergies';

COMMENT ON TABLE "patient_conditions" IS 'Many-to-many between patients and medical conditions';

COMMENT ON COLUMN "appointments"."status" IS 'pending, confirmed, completed, cancelled, no_show';

COMMENT ON TABLE "patient_treatments" IS 'Junction table: many-to-many between patients and treatments, with session details';

COMMENT ON COLUMN "patient_treatments"."status" IS 'planned, completed, cancelled';

COMMENT ON COLUMN "invoices"."status" IS 'draft, pending, paid, partial, overdue, cancelled';

COMMENT ON COLUMN "payments"."method" IS 'cash, card, bank_transfer, etc.';

COMMENT ON COLUMN "audit_logs"."details" IS 'JSON or plain text describing the change';

COMMENT ON COLUMN "medications"."form" IS 'tablet, capsule, syrup, injection, etc.';

COMMENT ON COLUMN "medications"."strength" IS '500 mg, 5 mg/mL, etc.';

COMMENT ON COLUMN "medications"."default_route" IS 'oral, IV, IM, topical, etc.';

COMMENT ON COLUMN "medications"."default_instructions" IS 'Optional: default dosage/notes';

COMMENT ON COLUMN "prescriptions"."appointment_id" IS 'optional, link when created from an appointment';

COMMENT ON COLUMN "prescriptions"."notes" IS 'general notes for the whole prescription';

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("doctor_id") REFERENCES "users" ("id");

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointments" ("id");

ALTER TABLE "prescription_items" ADD FOREIGN KEY ("prescription_id") REFERENCES "prescriptions" ("id");

ALTER TABLE "prescription_items" ADD FOREIGN KEY ("medication_id") REFERENCES "medications" ("id");

ALTER TABLE "expenses" ADD FOREIGN KEY ("category_id") REFERENCES "expense_categories" ("id");

ALTER TABLE "expenses" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("doctor_id") REFERENCES "users" ("id");

ALTER TABLE "patient_treatments" ADD FOREIGN KEY ("doctor_id") REFERENCES "users" ("id");

ALTER TABLE "patient_documents" ADD FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "patient_allergies" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "patient_conditions" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "patient_treatments" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "patient_documents" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "patient_allergies" ADD FOREIGN KEY ("allergy_id") REFERENCES "allergies" ("id");

ALTER TABLE "patient_conditions" ADD FOREIGN KEY ("condition_id") REFERENCES "medical_conditions" ("id");

ALTER TABLE "patient_treatments" ADD FOREIGN KEY ("treatment_id") REFERENCES "treatments" ("id");

ALTER TABLE "invoice_items" ADD FOREIGN KEY ("treatment_id") REFERENCES "treatments" ("id");

ALTER TABLE "patient_treatments" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointments" ("id");

ALTER TABLE "invoice_items" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id");
